name: Main
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby in Docker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ruby-test -f Dockerfile .

      - name: Run tests in Docker (retain container)
        run: |
          docker run --name ruby-test-container \
            -w /app \
            ruby-test \
            bundle exec rspec --require spec_helper

      - name: Copy coverage.json out of container
        run: |
          docker cp ruby-test-container:/app/coverage/coverage.json coverage.json

      - name: Cleanup container
        run: docker rm ruby-test-container

      - name: Check coverage file exists
        run: test -f coverage.json

      - uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: coverage.json
